---
- name: Install Nerd Fonts
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    home: "{{ lookup('ansible.builtin.env', 'HOME') }}"
    font_name: "DroidSansMNerdFont-Regular.otf"

  tasks:
    - name: Install Curl
      apt:
        name: curl
        state: present

    - name: Create Fonts Directory
      file:
        path: "{{ home }}/.local/share/fonts"
        state: directory
        mode: '0755'
        recurse: true

    - name: Download and Install Nerd Fonts
      shell: >
        curl -ssL https://github.com/ryanoasis/nerd-fonts/raw/HEAD/patched-fonts/DroidSansMono/{{ font_name }} -o /tmp/{{ font_name }}
        && mv /tmp/{{ font_name }} ~/.local/share/fonts/
      args:
        creates: "{{ home }}/.local/share/fonts/{{ font_name }}"

    - name: executable bit
      file:
        path: "{{ home }}/.local/share/fonts/{{ font_name }}"
        state: file
        mode: '0755'

    - name: Regenerate font cache
      shell: fc-cache -f

