---
- name: Install LunarVim and recommended Neovim version
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: Retrieve latest LunarVim release
      uri:
        url: https://api.github.com/repos/ChristianChiarulli/LunarVim/releases/latest
        return_content: true
        timeout: 5
      register: lunarvim_release

    - name: Extract LunarVim release version
      set_fact:
        lunarvim_version: "{{ lunarvim_release.json.tag_name }}"

    - name: Extract LunarVim branch name
      set_fact:
        lunarvim_branch: "{{ lunarvim_release.json.target_commitish }}"

    - name: Extract Neovim version from LunarVim branch name
      set_fact:
        neovim_version: "{{ lunarvim_branch.split('/')[-1].split('-')[-1] }}"

    - name: Check if Neovim is installed
      command: "which nvim"
      register: neovim_path
      changed_when: false
      failed_when: false

    - name: Get installed Neovim version
      command: "nvim --version | awk 'NR==1{print substr($2, 1, 3)}'"
      changed_when: false
      register: installed_neovim_version
      when: neovim_path.rc == 0

    - name: Install Neovim package
      become: true
      snap:
        name: nvim
        state: present
        classic: true
        channel: stable
      when: neovim_path.rc != 0 or (installed_neovim_version is defined and installed_neovim_version.stdout != neovim_version)

    - name: Install Cargo package
      become: true
      package:
        name: cargo
        state: present

    - name: Set up LunarVim
      shell: |
        LV_BRANCH={{ lunarvim_branch }} bash <(curl -s https://raw.githubusercontent.com/ChristianChiarulli/LunarVim/{{ lunarvim_branch }}/utils/installer/install.sh) -s -- --install-dependencies -y
      args:
        executable: /bin/bash
      register: install_lvim
      # Workaround on the problem https://github.com/LunarVim/LunarVim/issues/3612
      failed_when: false

    - name: check if lvim was installed but problem failed because 3612
      command: "lvim --version"
      register: lvim_version
      changed_when: false
      failed_when: false

    - name: really failed installation
      ansible.builtin.debug:
        var: lvim_version.rc
      ansible.builtin.fail:
        msg: The lvim installation failed
      when: lvim_version.rc != 0

    - name: patch 3612 bug
      command: sed -i -e 's:^exec.* nvim:nvim:g' /home/jrivero/.local/bin/lvim
      when: lvim_version.rc != 0

    - name: Install external linters and tools
      become: true
      package:
        name: ansible-lint shellcheck
        state: present
      when: lvim_version.rc == 0
